var english={
	"name": {
		"name": "en"
	},
	"_front": {
		"Cancel": "Cancel",
		"Confirm": "Confirm",
		"About_Us": "About Us",
		"Account": "Account",
		"UP": "UP",
		"Libiray": "Library",
		"Help": "Help",
		"My_Account": "My Account",
		"Setting": "Setting",
		"Share": "Share",
		"Skin": "Skin",
		"Language": "Language",
		"Current_Language": "Current Language",
		"Printer": "Printer",
		"No_UP_printers_found": "No UP printers found",
		"Failed_to_connect": "Failed to connect",
		"Connecting": "Connecting...",
		"Printer_Name_Cannot_Be_Empty": "Printer Name Cannot Be Empty.",
		"Failed_to_locate_WiFi": "Failed to locate WiFi",
		"Set_Success": "Set Succeeded",
		"Please_Enter_Password": "Please Enter Password",
		"Upgrade": "Upgrade",
		"Current": "Current",
		"Your_System_is_UPtodate": "Your System is UP-to-date",
		"Remind_me_of_the_new_version": "Remind me of the new version",
		"Update": "Update",
		"Privacy_Policy": "Privacy Policy",
		"privacy": "Please review Tiertime Privacy Policy to know about the details of data collection of UP Studio.<br />You can choose to turn on or off the data collection function base on your preference.",
		"Details": "Details",
		"Skin_Color": "Skin Color",
		"Model_Color": "Model Color",
		"Current_Color": "Current Color",
		"Basic": "Basic",
		"Login": "Login",
		"Username_or_Email": "Username or Email",
		"Sign_In": "Sign In",
		"Sign_Up": "Sign Up",
		"Remember_Me": "Remember Me",
		"Forgot_Password": "Forgot Password?",
		"Login_Failed": "Login Failed",
		"User_Account_has_not_been_Activated": "User Account has not been Activated",
		"User_does_not_Existed": "User does not Existed",
		"Password_is_Incorrect": "Password is Incorrect",
		"Please_enter_your_username_and_password": "Please enter your username and password",
		"Please_enter_user_name": "Please enter user name",
		"Please_enter_your_password": "Please enter your password",
		"Network_Problems_and_Please_Try_Later": "Network Problems and Please Try Later",
		"Login_Timeout": "Login Timeout",
		"Printer_Management": "Printer Management",
		"Serial_Number": "Serial Number",
		"Activation_Status": "Activation Status",
		"Binding_Status": "Binding Status",
		"Activate": "Activate",
		"Activated": "Activated",
		"Bind": "Bind",
		"Unbind": "Unbind",
		"Success": "Success",
		"Unbind_Successfully": "Unbind Successfully",
		"Failed_to_Unbind": "Failed to Unbind",
		"Binding_Successfully": "Binding Successfully",
		"Activation_Succeeded": "Activation Succeeded",
		"Sign_out": "Sign out",
		"Username": "Username (3-20 Characters Starting with a Letter)",
		"Emailenter": "Email (Enter an Email Address)",
		"Password": "Password (6-32 Characters)",
		"Confirm_Password": "Confirm Password (Input Password Again)",
		"Registration_means_you_agree_with": "Registration means you agree with",
		"Tiertime_End_User_Agreement": "Tiertime End User Agreement",
		"Invalid_Username": "Invalid Username",
		"Invalid_Email_Address": "Invalid Email Address",
		"Invalid_Password": "Invalid Password",
		"Passwords_Do_Not_Match": "Passwords Do Not Match",
		"Username_has_been_used": "Username has been used.",
		"Email_account_has_been_used": "Email account has been used.",
		"Registration_Successful": "Registration Successful",
		"Congratulations": "Congratulations",
		"success_text": "Registration is successful. An activation code has been sent to your email account. Please click the link in your email to activate your account.",
		"Email": "Email",
		"Error": "Error",
		"Email_or_Username_Error": "Email or Username Error",
		"An_email_to_reset_your_password_has_been_sent_to_your_email_address": "An email to reset your password has been sent to your email address",
		"Failed_to_Reset_Password": "Failed to Reset Password",
		"Home": "Home",
		"Import_Model_or_Image": "Import Model or Image",
		"Print": "Print",
		"Initialize_Printer": "Initialize Printer",
		"Calibrate": "Calibrate",
		"Maintenance": "Maintenance",
		"Move": "Move",
		"Scale": "Scale",
		"More": "More",
		"View": "View",
		"Undo": "Undo",
		"Auto_Place": "Auto Place",
		"Rotate": "Rotate",
		"Mirror": "Mirror",
		"Save_Model": "Save Model",
		"Reset_to_Default": "Reset to Default",
		"Fix_Errors": "Fix Errors",
		"Merge": "Merge",
		"Delete": "Delete",
		"Top_View": "Top View",
		"Bottom_View": "Bottom View",
		"Back_View": "Back View",
		"Free_View": "Free View",
		"Right_View": "Right View",
		"Front_View": "Front View",
		"Left_View": "Left View",
		"Wait_a_moment": "Wait a moment...",
		"Range_is_from": "Range is from",
		"No_Axis_Chosen": "No Axis Chosen",
		"Add": "Add",
		"Add_Picture": "Add Picture",
		"Add_Mode": "Add Mode",
		"Saving": "Saving",
		"Printer_Setting": "Printer Setting",
		"Normal": "Normal",
		"Layer_Thickness": "Layer Thickness",
		"Infill": "Infill",
		"Quality": "Quality",
		"Fine": "Fine",
		"Fast": "Fast",
		"Turbo": "Turbo",
		"Option": "Option",
		"Preference": "Preference",
		"Dormancy": "Dormancy",
		"Preview": "Preview",
		"Select_Saved_Slot": "Select Saved Slot",
		"Reprint": "Reprint",
		"Slot": "Slot",
		"Number": "NO.",
		"Model_Name": "Model Name",
		"Time": "Time",
		"Date": "Date",
		"Choose": "Choose",
		"Part": "Part",
		"Surface": "Surface",
		"Angle": "Angle",
		"Support": "Support",
		"Dense": "Dense",
		"Area": "Area",
		"Space": "Space",
		"No_Raft": "No Raft",
		"No_Support": "No Support",
		"Stable_Support": "Stable Support",
		"Others": "Others",
		"Unsolid_Model": "Unsolid Model",
		"Thin_Wall": "Thin Wall",
		"Preheat": "Preheat",
		"Default": "Default",
		"Calibration": "Calibration",
		"Platform_Calibration": "Platform Calibration",
		"Manual": "Manual",
		"Auto_Level": "Auto Level",
		"Reset": "Reset",
		"Nozzle_Height": "Nozzle Height",
		"Set": "Set",
		"Nozzle_Detect": "Nozzle Detect",
		"Demo_Op": "Demo Op.",
		"Demo_Op_Over": "Demo Op. Over",
		"Set_nozzle_height_is": "Set nozzle height is:",
		"Compensation": "Compensation",
		"Set_Nozzle_Height_as": "Set Nozzle Height as ",
		"Platform_Auto_Calibration_in_Progress": "Platform Auto Calibration in Progress...",
		"Nozzle_Auto_Calibration_in_Progress": "Nozzle Auto Calibration in Progress...",
		"Please_Choose_Plate_Type": "Please Choose Plate Type",
		"Perforated": "Perforated",
		"Flex": "Flex",
		"Extrude": "Extrude",
		"Withdraw": "Withdraw",
		"Stop": "Stop",
		"Material": "Material",
		"Weight": "Weight",
		"Customized": "Customized",
		"Customized_Material": "Customized Material",
		"Name": "Name",
		"Nozzle": "Nozzle(℃)",
		"Platform": "Platform(℃)",
		"Process": "Process",
		"Please_sign_in_your_account": "Please sign in your account",
		"Material_Name_Duplicated": "Error:Material Name Duplicated",
		"Only_7_Materials_Allowed": "Only 7 Materials Allowed",
		"Fields_can_not_be_Empty": "Fields can not be Empty",
		"Please_Enter_Numbers": "Please Enter Numbers",
		"Only_Numbers_and_Characters_Allowed": "Only Numbers and Characters Allowed",
		"Stop_Printing": "Stop Printing",
		"Pause": "Pause",
		"Resume": "Resume",
		"Stop_Preview": "Stop Preview",
		"Confirm_to_Stop": "Confirm to Stop?",
		"Stop_the_Current_Print_Job": "Stop the Current Print Job?",
		"Time_Left": "Time Left",
		"h": "h",
		"m": "m",
		"s": "s",
		"Slicing": "Slicing",
		"Sending": "Sending",
		"offical_initerface": "Official Material",
		"series_number": "Serial Number",
		"serial_password": "Password",
		"please_series_number": "Please Enter The Serial Number",
		"My_model": "My Model",
		"Public_model": "Quality Model",
		"Self_model": "Private Model",
		"Save_model": "Collected Models",
		"Share_model": "Shared Model",
		"Buy_model": "Purchased Model",
		"My_print": "My 3D Printer",
		"Find_all_print": "View All Printers",
		"User_number": "User Credits",
		"Change_password": "Modify Password",
		"upload_model": "Upload Model",
		"upload": "Upload",
		"upload_list": "Upload List",
		"readmessage": "Preparing Data......",
		"All": "All",
		"Free": "Free of Charge",
		"Pay": "Charge",
		"Model_parameter": "Model Parameter",
		"Model_Size": "Model Size",
		"Model_price": "Model Price",
		"Model_filder": "Model File",
		"Print_count": "Print Times",
		"Model_buy": "Purchase Model",
		"Model_save": "Collection",
		"Model_al_save": "Collected",
		"Model_download": "Download Model",
		"Model_deleat": "Delete Model",
		"Model_desript": "Description of Model",
		"Model_name": "Model Name",
		"Download_on": "Download",
		"Model_share": "Share",
		"Cancel_upload": "Unpublish",
		"Upload_ing": "Review The Publish",
		"All_download": "Download All",
		"All_open": "Open All",
		"Model_attr": "Model Property",
		"Model_information": "Model Infomation",
		"Name_path": "FIle Name",
		"Filepath: ": "FIle Path:",
		"Size(mm): ": "Model SIze:",
		"Min-Size(mm): ": "Min Pos:",
		"Max-Size(mm): ": "Max Pos:",
		"Vertex Number: ": "Vertex Number:",
		"Facet Number: ": "Facet Number:",
		"Volume: ": "Volume(mm3):",
		"Surface_Area": "Area(mm2)",
		"Inch": "Inch",
		"Mm": "mm"
	},
	"print": {
		"PrinterStatus-1": "Printer not Connected",
		"PrinterStatus0": "Printer not Initialized",
		"PrinterStatus1": "Printer Ready",
		"PrinterStatus2": "Print Job in Progress",
		"PrinterStatus3": "Print Job Paused",
		"PrinterStatus4": "Nozzle Error",
		"PrinterStatus5": "Motion System Error",
		"PrinterStatus6": "Print Job Finished",
		"PrinterStatus7": "Print Job Stopped",
		"PrinterStatus8": "Nozzle Too Hot",
		"PrinterStatus9": "Nozzle Too Cool",
		"PrinterStatus10": "Platform Too Hot",
		"PrinterStatus11": "tt_reserved_1",
		"PrinterStatus12": "tt_reserved_2",
		"PrinterStatus13": "tt_reserved_3",
		"PrinterStatus14": "tt_reserved_4",
		"PrinterStatus15": "System Powered ON",
		"PrinterStatus16": "SD Card Error",
		"PrinterStatus17": "SD Card Write Error",
		"PrinterStatus18": "SD Card Read Error",
		"PrinterStatus19": "Save to SD Card",
		"PrinterStatus20": "Joggle Error",
		"PrinterStatus21": "Copyright Limitation",
		"PrinterStatus22": "Print Number Limitation",
		"PrinterStatus23": "Communication Error",
		"ERROR": "ERROR",
		"ERROR: Task cannot be performed during printing": "ERROR: Task cannot be performed during on going print jobs.",
		"ERROR: Incorrect material": "ERROR: Incorrect Material.",
		"ERROR: Printer status error": "ERROR: Printer Status Error.",
		"ERROR: Slicing error": "ERROR: Slicing Error.",
		"ERROR: Printer connection error": "ERROR: Printer Connection Error.",
		"ERROR: Data transfer failure": "ERROR: Data Transfer Failure.",
		"ERROR: Printer is busy,please stop and try again": "ERROR: Printer is busy. Please wait until it stops and then try again.",
		"ERROR: Printer material shortage,still continue?": "ERROR: Printer is short of material, still continue?",
		"ERROR: Printer support material shortage,still continue?": "ERROR: Printer is short of support material, still continue?",
		"ERROR: Nozzleheight set error</br>Correct range:": "ERROR: Failed to set Nozzle height</br>Correct range:",
		"Repeat last print?": "Repeat Last Print?",
		"ERROR: Other error ": "ERROR: Other Errors.",
		"Language test": "Language Test",
		"Are you sure to stop the print job?": "Confirm to stop the current print job?",
		"Found a new version": "A new version of software has been found",
		",download it immediately?": ",download it immediately?",
		"[YES]: Update immediately": "[YES]: Update Immediately",
		"[NO]: Remind me later": "[NO]: Remind Me Later",
		"[CANCEL]: Switch off update reminder": "[CANCEL]: Switch Off Update Reminder",
		"Note: Download will be running in the background, after the completion of the notice": "Note: Download will be running in the background. You will be notified after the completion .",
		"Update": "Update",
		"No new version": "No New Version.",
		"ERROR: The model is opening, please try again later": "ERROR: The model is being loaded. Please try again later.",
		"ERROR: Temperature is too high": "ERROR: Temperature is too high.",
		"ERROR: Sensor not connected": "ERROR: Sensor is not connected.",
		"ERROR: Calibration failure": "ERROR: Calibration failed.",
		"ERROR: Printer is busy": "ERROR: Printer is busy.",
		"Success，Please reset nozzle height before printing": "Success: Please reset the nozzle height before printing.",
		"ERROR: Printer error": "ERROR: Printer Error.",
		"Print: ": "Print: ",
		"Material: ": "Material: ",
		"g": "g",
		"H": "H",
		"M": "M",
		"S": "S",
		"ERROR: Templete directory get error": "ERROR: Failed to locate the temporary directory.",
		"ERROR: Create dir error": "ERROR: Failed to create directory",
		"ERROR: Copy UpdateFile Error_APP": "ERROR: Failed to Copy Update File_APP",
		"ERROR: Copy UpdateFile Error_DLL": "ERROR: Failed to Copy Update File_DLL",
		"ERROR: Nozzleheight set error": "ERROR: Failed to Set Nozzle Height",
		"ERROR:Model does not exist": "ERROR: Model not found",
		"Activation": "Activation",
		"Please activate the printer in time to use the full printer functions": "Please activate the printer to use the full power of UP Printers",
		"Activation state error, need to return to the factory": "Failed to activate the printer. Please contact the manufacturer.",
		"OK": "OK",
		"CANCEL": "CANCEL",
		"YES": "YES",
		"NO": "NO",
		"ABORT": "ABORT",
		"RETRY": "RETRY",
		"IGNORE": "IGNORE",
		"Save successful": "Save succeeded.",
		"Save failed": "Save failed.",
		"Downloading, please wait": "Download in progress. Please wait.",
		",upgrade now?": ",upgrade now?",
		"Level data save error": "Failed to Save Leveling Data.",
		"ERROR: Printer no response": "ERROR: Printer not Responding.",
		"ERROR: Printer password error": "ERROR: Incorrect Printer Password.",
		"ERROR: Printer connected by other clients": "ERROR: Printer is being used by other users.",
		"ERROR: Printer none certification": "ERROR: Printer is not certified.",
		"Connection OK": "Connection OK.",
		"Connection Error": "Connection Error.",
		"Activation is successful, please restart the printer": "Activation succeeded. Please restart the printer.",
		"Can not Save more than 4 millon facets model": "Cannot save models with more than 4 million facets.",
		"No Model Selected": "No model is selected",
		"warning!": "Warning!",
		"    Delete Selected Model?": "    Delete Selected Models?",
		"    Delete All Models?": "    Delete all of Models?",
		"Please close the front door": "Please Close the Front Door.",
		"Model is too large! Can not Load": "Model is too large. Loading Failed",
		"Loading Failed": "Loading Failed!",
		"Print job stopped at ": "Print Job Stopped at layer No.",
		"th layer, resume the print?": ". Resume the Print Job?",
		"ERROR:  Can not resume the broken print job": "Error: Can not resume the suspended print",
		"ERROR: Data transfer failed, try again?": "ERROR: Data Transfer Failed. Try again?",
		"OpenGL Version Too Low! Check your Graphic Drivers!": "Please upgrade OpenGL, and check your graphic card drivers!",
		"ERROR: Printer SN Error": "ERROR: Printer Serial Number Error",
		"ERROR: Unknow error": "ERROR: Unknown Error",
		"ERROR: Invalide activekey": "ERROR: Invalid Activation Key",
		"ERROR: No factory actived": "ERROR: Not Factory Activated",
		"ERROR: Active error,wrong key": "ERROR: Activation Error. Invalid Key",
		"ERROR: The server returns the activation code to parse the JSON failed": "ERROR: Activation data returned from server failed.",
		"ERROR: The server failed to return the activation code": "ERROR: The server failed to return the activation code",
		"ERROR: Failed to get the check code from the printer": "ERROR: Failed to get the checksum data from the printer",
		"ERROR: The current state of activation is not factory activation": "ERROR: The current activation status is not factory activation",
		"ERROR: Failed to obtain an active state": "ERROR: Failed to obtain the activation status.",
		"ERROR: Model out of print bound": "ERROR: Model out of Bound of Print Area",
		"ERROR: Calibration Failure": "ERROR: Calibration Failed",
		"ERROR: Server connection failed": "ERROR: Server Connection Failed",
		"ERROR: Verification Failed,Please download activation package": "ERROR: Verification Failed. Please Download Activation Package",
		"[YES] Perf Board[NO] Flex Board": "",
		"Please Select The Type Of Plat": "Please Select the Type Of Plat",
		"ERROR: Temperature is low": "ERROR: Temperature is Low",
		"Do you want to keep current model?": "Do you want to keep current model?",
		"ERROR: Image read failed": "Error: Image import failed",
		"Multiple": "Multiple",
		"ERROR：Please select the model you need to upload": "Error: Please select the model you need to uplaod",
		"Initialize_Printer": "Initialize Printer",
        "ERROR: Material modification failure": "ERROR: Material modification failure",
        "Price":"Price",
		"Point":"Point",
		"Sure to buy":"Do you want get this project"
	},
	"graphic": {
		"Filepath: ": "File Path: ",
		"Size(mm): ": "Size(mm): ",
		"Min-Size(mm): ": "Min-Size(mm): ",
		"Max-Size(mm): ": "Max-Size(mm): ",
		"Vertex Number: ": "Vertex Number: ",
		"Facet Number: ": "Facet Number: ",
		"Volume: ": "Volume: ",
		"Copying...": "Copying Models ...",
		"Saveing...": "Saving Models ...",
		"has scaled from inch unit to mm unit!": "Model is too small,Enlarged by 25.4(inch) times!",
		"Property": "Property",
		"Merge": "Merge Model",
		"Copy": "Copy",
		"1 model": "1 Copy",
		"2 model": "2 Copys",
		"5 model": "5 Copys",
		"Delete": "Delete",
		"Delete All": "Delete All",
		"Select All": "Select All",
		"UnSelect All": "Unselect All",
		"Initialize View": "Initialize View",
		"Rotate By Models Center": "Rotate around the Center of Models",
		"Exit": "Exit"
	},
	"image_front": {
		"_Model_Height": "Model Height",
		"_Base_Height": "Base Height",
		"_Style": "Style",
		"_Model_Size": "Model Size",
		"_Unit": "Unit(mm)",
		"_Pen_Size": "Pen Size",
		"_Pen_Color": "Pen Color",
		"_Pen_Type": "Pen Type",
		"_Erase_Size": "Erase Size",
		"_Font": "Font",
		"_Font_Size": "Font Size",
		"_Font_Color": "Font Color",
		"_Constrain": "Constrain",
		"_Tools": "Tools",
		"_Setting": "Setting",
		"_Previous": "Previous",
		"_Apply": "Apply",
		"_Go_back": "Back",
		"_Pen": "Pen",
		"_Rubber": "Eraser",
		"_Text": "Text",
		"_Cut": "Crop",
		"_Toggle_color": "Toggle color"
	},
	"IOS_Ipad_Iphone":{
    "Version":"1.0.1",
    "name": "en",
    "Stop": "Stop",
    "Extrude":"Extrude",
    "WithDraw":"WithDraw",
    "SN":"NO.",
    "ModelName":"Model name",
    "Archive":"Slot",
    "Infill":"Infill",
    "Register_success":"Register success",
    "Congratulation":"Congratulation",
    "ActivationCode":"Register successfully,active code has been sent to your email-box,please clicked and active your account.",
    "systemError": "System error",
    "tt_systemunlink": "Printer not connected",
    "tt_systemerror": "No initialization",
    "tt_prepared": "Printer ready",
    "tt_runing": "Printing",
    "tt_pause": "Printing paused",
    "tt_nozzleerror": "Nozzle error",
    "tt_motionerror": "Motion system error",
    "tt_finished": "Print job finished",
    "tt_userstop": "Print job stopped",
    "tt_temphigh": "Nozzle too hot",
    "tt_templow": "Nozzle too Cool",
    "tt_workroomhigh": "Platform too hot",
    "tt_reverse_1": "tt_reverse_1",
    "tt_reverse_2": "tt_reverse_2",
    "tt_reverse_3": "tt_reverse_3",
    "tt_reverse_4": "tt_reverse_4",
    "tt_systempoweron": "System powered on",
    "tt_sdcarderror": "SD Card error",
    "tt_sdwberror": "SD Card writing error",
    "tt_sdrberror": "SD Card reading error",
    "tt_savetosd": "Save to SD Card",
    "tt_jogcmderror": "Joggle error",
    "tt_copyrightzero": "Copy right limitation",
    "tt_printtimelimit": "Print number limitation",
    "tt_commerror": "Communication error",
    "printerName": "PrinterName",
    "nozzleTemperature": "Nozzle TEMP",
    "flatTemperature": "Plat TEMP",
    "m_nMaterial": "Material",
    "m_dNozzleHeight": "Nozzle Height",
    "btn_aboutUs": "About us",
    "btn_myCounts": "Account",
    "btn_up": "UP",
    "btn_libiray": "Library",
    "btn_help": "Help",
    "dialogTitle_add": "ADD",
    "dialogAdd_photo": "Add Photo",
    "dialogAdd_stl": "Add Model",
    "dialogTitle_layer": "Setting",
    "dialogTitle_Z_resolution": "Layer Thick",
    "dialogTitle_part": "Part",
    "dialogTitle_Surface": "Surface",
    "dialogTitle_Surface_SupportAngle": "Angle",
    "dialogTitle_Support": "Support",
    "dialogTitle_Dense": "Dense",
    "dialogTitle_Support_Angle": "Angle",
    "dialogTitle_Support_Area": "Area",
    "dialogTitle_Support_Space": "Space",
    "dialogTitle_Stable_Support": "Stable Support",
    "dialogTitle_Fill": "Fill",
    "dialogTitle_fill_shell": "Shell",
    "dialogTitle_fill_surface": "Surface",
    "dialogTitle_fill_solid": "Solid",
    "dialogTitle_fill_Loose": "Loose",
    "dialotTitle_fill_Hollow": "Hollow",
    "dialogTitle_fill_BigHole": "Big Hole",
    "ResettoDefault": "Default",
    "save": "Save",
    "unsave": "Cancel",
    "dialogTitle_Maintain": "Maintenance",
    "dialogTitle_Maintenance": "Maintenance",
    "dialogTitle_Extrude": "Extrude",
    "dialogTitle_Evacuate": "Withdraw",
    "Stop": "Stop",
    "Weight": "Weight",
    "dialogTitle_PrinterSetting": "Printer Setting",
    "dialogTitle_printerName": "Printers",
    "dialogTitle_UnsolidModel": "Unsolid Model",
    "dialogTitle_NoRaft": "No Raft",
    "dialogTitle_heat": "Keep Heating",
    "dialogTitle_Quality": "Quality",
    "option": "Option",
    "reprint": "Reprint",
    "preview": "Preview",
    "dialogTitle_Calibrate": "Calibration",
    "platMainH3": "Platform Correction",
    "printBtn": "Print",
    "exit": "exit",
    "save3DModeling_txt": "Saving",
    "ImgTo3D_txt": "Reversing",
    "Time_left": "Time",
    "initialPrinter": "initialPrinter ing",
    "logIn": "Sign in",
    "preference": "Preference",
    "option": "Option",
    "no_Support": "No Support",
    "thinWall": "Thin Wall",
    "others": "Others",
    "autoPlace": "Auto Place",
    "noRecentFile": "No Recent File",
    "autoUpdateTxt": "Please remind me of the new version",
    "apError": "Wifi Error",
    "auto": "Auto",
    "manual": "Manual",
    "platAutoIng": "Plat Auto Calibrate",
    "nozzleAutoIng": "Nozzle Auto Calibrate",
    "autoError": "Sensor not connected",
    "errorTxt": "Error",
    "successTxt": "Success",
    "connectTxt": "Connecting...",
    "setSuccessTxt": "Set Success ",
    "setErrorTxt": "Set Failure",
    "convert": "Converting",
    "nozzleHeating": "Wait a moment",
    "math": "slicing",
    "transfer": "transfer",
    "normal": "Normal",
    "fine": "Fine",
    "fast": "Fast",
    "timeH": "h",
    "timeM": "m",
    "timeS": "s",
    "connectSuccessTxt": "Connect Success ",
    "connectErrorTxt": "Connect Failure",
    "languageTxt": "Language",
    "PrinterTxt": "Printer",
    "wifiTxt": "Wifi",
    "UpdateTxt": "Update",
    "currentTxt": "Current",
    "newTxt": "Latest",
    "axisTxt": "Not choose axis direction",
    "yes": "Confirm",
    "no": "Cancel",
    "printerInitTips": "Is the printer initialized?",
    "printerStopTips": "Do you want to stop printing?",
    "manualUpdate": "Update",
    "justTxt1": "Just enter",
    "justTxt2": "number",
    "nameError": "Printer name can not be empty",
    "custom": "Custom",
    "txtObject": "Object",
    "share": "share",
    "verTips": "Your system is up to date ",
    "nozzleCurrentHeight": "Nozzle Current Height",
    "nozzleSetHeight": "Nozzle Height",
    "reset": "Reset",
    "compensation": "Leveling",
    "pausePrintError": "Pause Print Error",
    "resumePrintError": "Resume Print Error",
    "nozzleTo": "Move",
    "set": "Set",
    "detectNozzle": "Detect Nozzle",
    "autoLevel": "Auto Level",
    "saveSetNozzleHeight": "Save nozzle height as ",
    "intNumberTips": "Range is from",
    "connectWifiError0x110": "Password error",
    "connectWifiError0x111": "Connected by other clients",
    "connectWifiError0x112": "None certification",
    "connectWifiError0x113": "Can't connected",
    "connectWifiError0": "No response",
    "connectWifiError2": "Printer busy",
    "connectWifiErrorUnknown": "Unknown error",
    "sync_tips_resetPrinter":"Reset Printer",
    "checkNetwork":"Please check the network, and ensure that the App connection routing agreement with printer",
    "previewStopTips": "Do you want to stop preview?",
    "ios_Font_WordStyle"  : "WordStyle",
    "ios_Font_Keyboard"   : "Keyboard",
    "ios_Font_Finish"     : "Finish",
    "ios_Font_ChangeText" : "ChangeText:",
    "ios_Font_Font"       : "Font",
    "ios_Font_PleaseChangWord"  : "Please click to enter text ",
    "ios_Alert_Message"  : "Model improted, open now? ",
    "ios_Alert_cancel"   : "Cancel",
    "ios_Alert_OK"       : "OK",
    "ERROR": "ERROR",
    "ERROR: Task cannot be performed during printing": "ERROR: Task cannot be performed during printing",
    "ERROR: Incorrect material": "ERROR: Incorrect material",
    "ERROR: Printer status error": "ERROR: Printer status error",
    "ERROR: Slicing?error": "ERROR: Slicing?error",
    "ERROR: Printer connection error": "ERROR: Printer connection error",
    "ERROR: Data transfer failure": "ERROR: Data transfer failure",
    "ERROR: Printer is busy,please stop and try again": "ERROR: Printer is busy,please stop and try again",
    "ERROR: Printer?material?shortage,still continue?": "ERROR: Printer?material?shortage,still continue?",
    "ERROR: Printer support material shortage,still continue?": "ERROR: Printer support material shortage,still continue?",
    "ERROR: Nozzleheight set error\nCorrect range:": "ERROR: Nozzleheight set error\nCorrect range:",
    "Repeat last print?": "Repeat last print?",
    "ERROR: Other error ": "ERROR: Other error ",
    "Language test": "Language test",
    "Are you sure to stop the print job?": "Are you sure to stop the print job?",
    "Found a new version": "Found a new version",
    ",download it immediately?": ",download it immediately?",
    "[YES]: Update immediately": "[YES]: Update immediately",
    "[NO]: Remind me later": "[NO]: Remind me later",
    "[CANCEL]: Switch off update reminder": "[CANCEL]: Switch off update reminder",
    "Note: Download will be run in the background, after the completion of the notice": "Note: Download will be run in the background, after the completion of the notice",
    "Update": "Update",
    "No new version": "No new version",
    "ERROR: The model is opening, please try again later": "ERROR: The model is opening, please try again later",
    "ERROR: Temperature is too high": "ERROR: Temperature is too high",
    "ERROR: Sensor not connected": "ERROR: Sensor not connected",
    "ERROR: Calibration failure": "ERROR: Calibration failure",
    "ERROR: Printer is busy": "ERROR: Printer is busy",
    "Success£¬Please reset nozzle height before printing": "Success£¬Please reset nozzle height before printing",
    "ERROR: Printer error": "ERROR: Printer error",
    "Print: ": "Print: ",
    "Material: ": "Material: ",
    "g": "g",
    "H": "H",
    "M": "M",
    "S": "S",
    "ERROR: Templete directory get error": "ERROR: Templete directory get error",
    "ERROR: Create dir error": "ERROR: Create dir error",
    "ERROR: Copy UpdateFile Error_APP": "ERROR: Copy UpdateFile Error_APP",
    "ERROR: Copy UpdateFile Error_DLL": "ERROR: Copy UpdateFile Error_DLL",
    "ERROR: Nozzleheight set error": "ERROR: Nozzleheight set error",
    "ERROR:Model does not exist": "ERROR:Model does not exist",
    "Activation": "Activation",
    "Please activate the printer in time to use the full printer functions": "Please activate the printer in time to use the full printer functions",
    "Activation state error, need to return to the factory": "Activation state error, need to return to the factory",
    "OK": "OK",
    "CANCEL": "CANCEL",
    "YES": "YES",
    "NO": "NO",
    "ABORT": "ABORT",
    "RETRY": "RETRY",
    "IGNORE": "IGNORE",
    "Save successful": "Save successful",
    "Save failed": "Save failed",
    "Downloading, please wait": "Downloading, please wait",
    ",upgrade now?": ",upgrade now?",
    "Level data save error": "Level data save error",
    "ERROR: Printer no response": "ERROR: Printer no response",
    "ERROR: Printer password error": "ERROR: Printer password error",
    "ERROR: Printer connected by other clients": "ERROR: Printer connected by other clients",
    "ERROR: Printer none certification": "ERROR: Printer none certification",
    "Connection OK": "Connection OK",
    "Connection Error": "Connection Error",
    "Activation is successful, please restart the printer": "Activation is successful, please restart the printer",
    "Can not Save more than 4 millon facets model": "Can not Save more than 4 millon facets model",
    "Please close the front door": "Please close the front door",
    "Can not Open more than 1 millon facets temporarily in WIN32 System": "Can not Open more than 1 millon facets temporarily in WIN32 System",
    "Print job stopped at ": "Print job stopped at ",
    "th layer, resume the print?": "th layer, resume the print?",
    "ERROR: Can't resume the broken print job": "ERROR: Can't resume the broken print job",
    "ERROR: Data transfer failed, try again?": "ERROR: Data transfer failed, try again?",
    "OpenGL Version Too Low! Check your Graphic Drivers!": "OpenGL Version Too Low! Check your Graphic Drivers!",
    "UnknownName": "UnknownName",
    "Please input" : "Please input ",
    "'s password" : " 's password",
    "Enter password" : "Enter password",
    "Join" : "JOIN",
    "Joining" : "Joining ",
    "Cannot Join" : "Cannot Join ",
    "user_login":"Login",
    "user_name_hint":"Email/Username",
    "password_hint":"Password",
    "sign_in":"Login in",
    "sign_up":"Sign up",
    "ifremember":"Remember Me",
    "forget_password":"Forgot password?",
    "username":"Username",
    "email":"Email",
    "ConfirmPassword":"Confirm password",
    "username_error":"username is illegal",
    "email_error":"email is illegal",
    "password_error":"password is illegal",
    "confirm_error":"two password is different",
    "registration_statement":"If you registed means you agree with",
    "agreement":"《Tiertime user agreement》",
    "login_info":"Printer Management",
    "online_device":"Device online",
    "Device_List":"My Printers",
    "my_device":"My devices",
    "net_error":"Internet is wrong",
    "device_sn":"NO.",
    "activate_status":"Activation Status",
    "bind_status":"Binding Status",
    "activate":"Active",
    "activated":"Actived",
    "bind":"Binding Status",
    "binded":"Binded",
    "unbind":"Unbine",
    "EmailWrong":"User name or email error",
    "UserNameExisted":"User name has been existed",
    "EmailExisted":"Email has been existed",
    "unactive":"Unactive",
    "PasswordErr":"Password error",
    "ERROR: Printer SN Error": "ERROR: Printer SN Error",
    "ERROR: Unknow error": "ERROR: Unknow error",
    "ERROR: Invalide activekey": "ERROR: Invalide activekey",
    "ERROR: No factory actived": "ERROR: No factory actived",
    "ERROR: Active error,wrong key": "ERROR: Active error,wrong key",
    "ERROR: The server returns the activation code to parse the JSON failed": "ERROR: The server returns the activation code to parse the JSON failed",
    "ERROR: The server failed to return the activation code": "ERROR: The server failed to return the activation code",
    "ERROR: Failed to get the check code from the printer": "ERROR: Failed to get the check code from the printer",
    "ERROR: The current state of activation is not factory activation": "ERROR: The current state of activation is not factory activation",
    "ERROR: Failed to obtain an active state": "ERROR: Failed to obtain an active state",
    "No Model saved for reprint": "No Model saved for reprint",
    "LoginError:User does not exist":"User does not exist",
    "LoginError:Password Error":"Password error",
    "LoginError:User not activated":"User not activated",
    "LoginError:Purchase of goods not registered":"Purchase of goods not registered",
    "LoginError:Registration parameter is not complete":"Registration parameter is not complete",
    "LoginError:Registration parameter check error":"Registration parameter check error",
    "LoginError:User already exists":"User already exists",
    "LoginError:Data save failed":"Data save failed",
    "LoginError:Network connection timeout":"Network connection timeout",
    "LoginError:Login failed,please try again":"Login failed,please try again",
    "The print model beyond the range":"The print model beyond the range",
    "Password has been successfully sent to the mailbox":"Password has been successfully sent to the mailbox",
    "Sign_out":"Sign out",
    "ERROR: Validation failure!":"ERROR: Validation failure!",
    "Logining...":"Logging in...",
    "Set_InitPrinter":"Initialize",
    "Set_StopPreview":"Stop Preview",
    "Set_StopPrint":"Stop Printing",
    "Set_Delete":"Delete",
    "Set_SelectPrinter":"Select Printer",
    "Set_MaterialName":"Name",
    "Set_MaterialInputName":"please input name",
    "Set_MaterialInputTemp":"please input temperature",
    "Set_Custom":"Customize",
    "Set_PlesaeInputMaterialName":"Enter material name",
    "Set_PleaseInput1-5Character":"Please enter a 1-5 digit character",
    "Set_NameExist":"Name already exists",
    "Set_Please enter a temperature value":"Please enter a temperature value",
    "Set_The temperature is not legitimate, please enter 0-300 numbers":"The temperature is not legitimate, please enter 0-300 numbers",
    "Set_The temperature is not legitimate, please enter 0-100 numbers":"The temperature is not legitimate, please enter 0-100 numbers",
    "Set_incomplete parameters":"incomplete parameters",
    "Set_Customize the amount of material can not be more than 4":"Customize the amount of material can not be more than 4",
    "Can not use special characters":"Can not use special characters",
    "Pause Printing":"Pause",
    "Resume printing":"Resume"
}

}
