var english={
    "version": "1.2",
    "date": "2016-9-12",
    "_front": {
        "name": "en",
        "systemError": "System Error",
        "tt_systemunlink": "No UP printers found",
        "tt_systemerror": "Printer not Initialized",
        "tt_prepared": "Printer Ready",
        "tt_runing": "Print Job in Progress",
        "tt_pause": "Print Job Paused",
        "tt_nozzleerror": "Nozzle Error",
        "tt_motionerror": "Motion System Error",
        "tt_finished": "Print Job Finished",
        "tt_userstop": "Print Job Stopped",
        "tt_temphigh": "Nozzle Too Hot",
        "tt_templow": "Nozzle Too Cool",
        "tt_workroomhigh": "Platform Too Hot",
        "tt_reverse_1": "tt_reverse_1",
        "tt_reverse_2": "tt_reverse_2",
        "tt_reverse_3": "tt_reverse_3",
        "tt_reverse_4": "tt_reverse_4",
        "tt_systempoweron": "System Powered ON",
        "tt_sdcarderror": "SD Card Error",
        "tt_sdwberror": "SD Card Write Error",
        "tt_sdrberror": "SD Card Read Error",
        "tt_savetosd": "Save to SD Card",
        "tt_jogcmderror": "Joggle Error",
        "tt_copyrightzero": "Copyright Limitation",
        "tt_printtimelimit": "Print Number Limitation",
        "tt_commerror": "Communication Error",
        "printerName": "Printer Name",
        "nozzleTemperature": "Nozzle(℃)",
        "flatTemperature": "Platform(℃)",
        "m_nMaterial": "Material",
        "printerTxt": "Printer Name",
        "m_dNozzleHeight": "Nozzle Height",
        "btn_aboutUs": "About Us",
        "btn_myCounts": "Account",
        "btn_up": "UP",
        "btn_libiray": "Library",
        "btn_help": "Help",
        "dialogTitle_add": "Add",
        "dialogAdd_photo": "Add Picture",
        "dialogAdd_stl": "Add Model",
        "dialogTitle_layer": "Setting",
        "dialogTitle_Z_resolution": "Layer Thickness",
        "dialogTitle_part": "Part",
        "dialogTitle_Surface": "Surface",
        "dialogTitle_Surface_SupportAngle": "Angle",
        "dialogTitle_Support": "Support",
        "dialogTitle_Dense": "Dense",
        "dialogTitle_Support_Angle": "Angle",
        "dialogTitle_Support_Area": "Area",
        "dialogTitle_Support_Space": "Space",
        "dialogTitle_Stable_Support": "Stable Support",
        "dialogTitle_Fill": "Infill",
        "dialogTitle_fill_shell": "Shell",
        "dialogTitle_fill_surface": "Surface",
        "dialogTitle_fill_solid": "Solid",
        "dialogTitle_fill_Loose": "Loose",
        "dialotTitle_fill_Hollow": "Hollow",
        "dialogTitle_fill_BigHole": "Big Hole",
        "ResettoDefault": "Default",
        "save": "Save",
        "unsave": "Cancel",
        "dialogTitle_Maintain": "Maintenance",
        "dialogTitle_Maintenance": "Maintenance",
        "dialogTitle_Extrude": "Extrude",
        "dialogTitle_Evacuate": "Withdraw",
        "Stop": "Stop",
        "Weight": "Weight",
        "dialogTitle_PrinterSetting": "Printer Setting",
        "dialogTitle_printerName": "Printers",
        "dialogTitle_UnsolidModel": "Unsolid Model",
        "dialogTitle_NoRaft": "No Raft",
        "dialogTitle_heat": "Keep Heating After Print Job Finished",
        "dialogTitle_Quality": "Quality",
        "option": "Option",
        "reprint": "Reprint",
        "preview": "Preview",
        "dialogTitle_Calibrate": "Calibration",
        "platMainH3": "Platform Calibration",
        "printBtn": "Print",
        "exit": "Exit",
        "save3DModeling_txt": "Saving",
        "ImgTo3D_txt": "Conversing",
        "Time_left": "Time Left",
        "initialPrinter": "Printer Initializing",
        "logIn": "Login",
        "preference": "Preference",
        "no_Support": "No Support",
        "thinWall": "Thin Wall",
        "others": "Others",
        "autoPlace": "Auto Place",
        "noRecentFile": "No Recent File",
        "autoUpdateTxt": "Remind me of the new version",
        "apError": "Failed to locate WiFi",
        "auto": "Auto",
        "manual": "Manual",
        "platAutoIng": "Platform Auto Calibration in Progress...",
        "nozzleAutoIng": "Nozzle Auto Calibration in Progress...",
        "autoError": "Sensor not connected",
        "errorTxt": "Error",
        "successTxt": "Success",
        "connectTxt": "Connecting...",
        "setSuccessTxt": "Set Succeeded",
        "setErrorTxt": "Set Failed",
        "convert": "Converting",
        "nozzleHeating": "Wait a moment...",
        "math": "Slicing",
        "transfer": "Sending",
        "normal": "Normal",
        "fine": "Fine",
        "fast": "Fast",
        "timeH": "h",
        "timeM": "m",
        "timeS": "s",
        "connectSuccessTxt": "Connected",
        "connectErrorTxt": "Failed to connect",
        "languageTxt": "Language",
        "PrinterTxt": "Printer",
        "wifiTxt": "WiFi",
        "UpdateTxt": "Upgrade",
        "currentTxt": "Current",
        "newTxt": "Latest",
        "axisTxt": "No Axis Chosen",
        "yes": "Confirm",
        "no": "Cancel",
        "printerInitTips": "Initialize Printer?",
        "printerStopTips": "Stop the Current Print Job?",
        "manualUpdate": "Update",
        "justTxt1": "Just Enter",
        "justTxt2": "Number",
        "justTxt3": "",
        "nameError": "Printer Name Cannot Be Empty.",
        "custom": "Customized",
        "txtObject": "Object",
        "share": "Share",
        "verTips": "Your System is UP-to-date",
        "nozzleCurrentHeight": "Current Nozzle Height",
        "nozzleSetHeight": "Nozzle Height",
        "reset": "Reset",
        "compensation": "Leveling",
        "pausePrintError": "Failed to Pause Print Job",
        "resumePrintError": "Failed to Resume Print Job",
        "nozzleTo": "Move",
        "set": "Set",
        "detectNozzle": "Nozzle Detect",
        "autoLevel": "Auto Level",
        "saveSetNozzleHeight": "Set Nozzle Height as ",
        "intNumberTips": "Range is from",
        "previewStopTips": "Confirm to Stop?",
        "privacy": "Please review Tiertime Privacy Policy to know about the details of data collection of UP Studio.<br />You can choose to turn on or off the data collection function base on your preference.",
        "privacyTxt": "Privacy Policy",
        "privacyBtn": "Details",
        "tooltip_backIndexPages": "Home",
        "tooltip_add": " Import Model or Image",
        "tooltip_btnPrint": "Print",
        "tooltip_stopPrint": "Stop Printing",
        "tooltip_pausePrint": "Pause",
        "tooltip_resumePrint": "Resume",
        "tooltip_stopPreview": "Stop Preview",
        "tooltip_initPrinter": "Initialize Printer",
        "tooltip_btnPlat": "Calibrate",
        "tooltip_btnMar": "Maintenance",
        "tooltip_circle_move": "Move",
        "tooltip_circle_zoom": "Scale",
        "tooltip_circle_class": "More",
        "tooltip_circle_view": "View",
        "tooltip_circle_back": "Undo",
        "tooltip_circle_fit": "Auto Place",
        "tooltip_circle_rotate": "Rotate",
        "tooltip_circle_mirror": "Mirror",
        "tooltip_circle_save": "Save Model",
        "tooltip_circle_reset": "Reset to Default",
        "tooltip_circle_fixded": "Fix Errors",
        "tooltip_circle_merge": "Merge",
        "tooltip_circle_del": "Delete",
        "tooltip_view_top": "Top View",
        "tooltip_view_bottom": "Bottom View",
        "tooltip_view_back": "Back View",
        "tooltip_view_free": "Free View",
        "tooltip_view_right": "Right View",
        "tooltip_view_front": "Front View",
        "tooltip_view_left": "Left View",
        "tooltip_top_my": "My Account",
        "tooltip_top_setting": "Setting",
        "tooltip_top_share": "Share",
        "tooltip_top_skin": "Skin",
        "turbo": "Turbo",
        "EnterPwd": "Please Enter Password",
        "statusError": "Status Error",
        "EmailWrong": "Email or Username Error",
        "PasswordErr": "Please Enter Password with 6-32 Characters",
        "CodeErr": "Validation Code Error",
        "LoginFail": "Login Failed",
        "Email": "Email",
        "password": "Password",
        "code": " Validation Code",
        "reprint_location": "Slot",
        "reprint_number": "NO.",
        "model_name": "Model Name",
        "reprint_time": "Time",
        "reprint_date": "Date",
        "reprint_select": "Choose",
        "pre_heat": "Preheat",
        "custom_material": "Customized",
        "custom_material_title": "Customized Material",
        "material": "Material",
        "material_name": "Name",
        "nozzle_temp": "Nozzle(℃)",
        "baseboard_temp": "Platform(℃)",
        "operation": "Process",
        "edit": "Edit",
        "delete": "Delete",
        "add_material": "Add",
        "cancel": "Cancel",
        "materials_repeat": "Error:Material Name Duplicated",
        "materials_7": "Only 7 Materials Allowed",
        "cuatom_material_title": "Customized Material",
        "user_login": "Login",
        "user_name_hint": "Username or Email",
        "password_hint": "Password",
        "sign_in": "Sign In",
        "sign_up": "Sign Up",
        "ifremember": "Remember Me",
        "forget_password": "Forgot Password?",
        "username": "Username (3-20 Characters Starting with a Letter)",
        "email": "Email (Enter an Email Address)",
        "sign_up_password":"Password (6-32 Characters)",
        "ConfirmPassword": "Confirm Password (Input Password Again)",
        "username_error": "Invalid Username",
        "email_error": "Invalid Email Address",
        "password_error": "Invalid Password",
        "confirm_error": "Passwords Do Not Match",
        "registration_statement": "Registration means you agree with",
        "agreement": "Tiertime End User Agreement",
        "login_info": "Printer Management",
        "online_device": "My Printers",
        "my_device": "My Device",
        "net_error": "Network Problems and Please Try Later",
        "device_sn": "Serial Number",
        "activate_status": "Activation Status",
        "bind_status": "Binding Status",
        "activate": "Activate",
        "activated": "Activated",
        "bind": "Bind",
        "binded": "Bound",
        "unbind": "Unbind",
        "unbind_success":"Unbind Successfully",
        "unbind_fail":"Failed to Unbind",
        "bind_success":"Binding Successfully",
        "fail":"Failed",
        "activate_success":"Activation Succeeded",
        "user_unexist":"User does not Existed",
        "reset_fail":"Failed to Reset Password",
        "login_fail":"Failed to Login",
        "reset_email_success":"An email to reset your password has been sent to your email address",
        "no data cache":"No Data in Cache",
        "login timeout":"Login Timeout",
        "can not find sn device":"Cannot locate the device with the Serial Number",
        "Save failed":"Failed to Save",
        "password_wrong":"Password is Incorrect",
        "unactivate":"User Account has not been Activated",
        "un_signup":"Username is not registered",
        "Parameter is not complete":"Incomplete Parameters",
        "Parameters calibration error":"Parameters Check Error",
        "UserExists":"Username has been Used",
        "datasavefail":"Failed to Save Data",
        "signup_success":"Registration Successful",
        "congratulation":"Congratulations",
        "success_text":"Registration is successful. An activation code has been sent to your email account. Please click the link in your email to activate your account.",
        "change_pic":"Change image",
        "toggle_black_white":"Toggle color",
        "translate_to_3d_model":"Transform to 3D model",
        "back":"Return Back",
        "sure_to_translate":"Confirm to Transform？",
        "only_num":"Please Enter Numbers",
        "only_num_letter":"Only Numbers and Characters Allowed",
        "Select save slot":"Select Saved Slot",
        "Fill in the incomplete":"Fields can not be Empty",
        "UserNameExisted":"Username has been used.",
        "EmailExisted":"Email account has been used.",
        "Login_out":"Sign out",
        "please_login":"Please sign in your account",
        "software_skin":"Skin Color",
        "model_color":"Model Color",
        "now_color":"Current",
        "base_color":"Basic",
        "current_language":"Current Language",
        "baseHeight":"Base Height",
        "modelHeight":"Model Height",
        "sure": "Confirm",
        "selectPlatType": "Please Choose Plate Type",
        "perforated plate": "Perforated",
        "flex": "Flex",
        "enterLoginInfo": "Please enter your username and password",
        "enterUsername": "Please enter user name",
        "enterPassword": "Please enter your password",
        "restTitle":"Dormancy",
        "materialHeat":"Preheat",
        "platManSet":"Manual",
          "platManSetHeight":"Set nozzle height is:",
        "dialog_manu":"Demo Op.",
        "dialog_manu_end":"Demo Op. Over",
        "compensation":"Compensation",
	"modeInfoTitle":"Model Properties",
        "modeInfomMark":"Basic",
        "Filepath": "File Path: ",
        "Size": "Size(mm): ",
        "MinSize": "Min-Size(mm): ",
        "MaxSize": "Max-Size(mm): ",
        "Vertex":"Vertex Number: ",
        "Facet": "Facet Number: ",
        "Volume": "Volume(mm³): ",
        "area":"Surface area(mm²)："
    },
    "print": {
        "PrinterStatus-1": "Printer not Connected",
        "PrinterStatus0": "Printer not Initialized",
        "PrinterStatus1": "Printer Ready",
        "PrinterStatus2": "Print Job in Progress",
        "PrinterStatus3": "Print Job Paused",
        "PrinterStatus4": "Nozzle Error",
        "PrinterStatus5": "Motion System Error",
        "PrinterStatus6": "Print Job Finished",
        "PrinterStatus7": "Print Job Stopped",
        "PrinterStatus8": "Nozzle Too Hot",
        "PrinterStatus9": "Nozzle Too Cool",
        "PrinterStatus10": "Platform Too Hot",
        "PrinterStatus11": "tt_reserved_1",
        "PrinterStatus12": "tt_reserved_2",
        "PrinterStatus13": "tt_reserved_3",
        "PrinterStatus14": "tt_reserved_4",
        "PrinterStatus15": "System Powered ON",
        "PrinterStatus16": "SD Card Error",
        "PrinterStatus17": "SD Card Write Error",
        "PrinterStatus18": "SD Card Read Error",
        "PrinterStatus19": "Save to SD Card",
        "PrinterStatus20": "Joggle Error",
        "PrinterStatus21": "Copyright Limitation",
        "PrinterStatus22": "Print Number Limitation",
        "PrinterStatus23": "Communication Error",
        "ERROR": "ERROR",
        "ERROR: Task cannot be performed during printing": "ERROR: Task cannot be performed during on going print jobs.",
        "ERROR: Incorrect material": "ERROR: Incorrect Material.",
        "ERROR: Printer status error": "ERROR: Printer Status Error.",
        "ERROR: Slicing error": "ERROR: Slicing Error.",
        "ERROR: Printer connection error": "ERROR: Printer Connection Error.",
        "ERROR: Data transfer failure": "ERROR: Data Transfer Failure.",
        "ERROR: Printer is busy,please stop and try again": "ERROR: Printer is busy. Please wait until it stops and then try again.",
        "ERROR: Printer material shortage,still continue?": "ERROR: Printer is short of material, still continue?",
        "ERROR: Printer support material shortage,still continue?": "ERROR: Printer is short of support material, still continue?",
        "ERROR: Nozzleheight set error</br>Correct range:": "ERROR: Failed to set Nozzle height</br>Correct range:",
        "Repeat last print?": "Repeat Last Print?",
        "ERROR: Other error ": "ERROR: Other Errors.",
        "Language test": "Language Test",
        "Are you sure to stop the print job?": "Confirm to stop the current print job?",
        "Found a new version": "A new version of software has been found",
        ",download it immediately?": ",download it immediately?",
        "[YES]: Update immediately": "[YES]: Update Immediately",
        "[NO]: Remind me later": "[NO]: Remind Me Later",
        "[CANCEL]: Switch off update reminder": "[CANCEL]: Switch Off Update Reminder",
        "Note: Download will be running in the background, after the completion of the notice": "Note: Download will be running in the background. You will be notified after the completion .",
        "Update": "Update",
        "No new version": "No New Version.",
        "ERROR: The model is opening, please try again later": "ERROR: The model is being loaded. Please try again later.",
        "ERROR: Temperature is too high": "ERROR: Temperature is too high.",
        "ERROR: Sensor not connected": "ERROR: Sensor is not connected.",
        "ERROR: Calibration failure": "ERROR: Calibration failed.",
        "ERROR: Printer is busy": "ERROR: Printer is busy.",
        "Success，Please reset nozzle height before printing": "Success: Please reset the nozzle height before printing.",
        "ERROR: Printer error": "ERROR: Printer Error.",
        "Print: ": "Print: ",
        "Material: ": "Material: ",
        "g": "g",
        "H": "H",
        "M": "M",
        "S": "S",
        "ERROR: Templete directory get error": "ERROR: Failed to locate the temporary directory.",
        "ERROR: Create dir error": "ERROR: Failed to create directory",
        "ERROR: Copy UpdateFile Error_APP": "ERROR: Failed to Copy Update File_APP",
        "ERROR: Copy UpdateFile Error_DLL": "ERROR: Failed to Copy Update File_DLL",
        "ERROR: Nozzleheight set error": "ERROR: Failed to Set Nozzle Height",
        "ERROR:Model does not exist": "ERROR: Model not found",
        "Activation": "Activation",
        "Please activate the printer in time to use the full printer functions": "Please activate the printer to use the full power of UP Printers",
        "Activation state error, need to return to the factory": "Failed to activate the printer. Please contact the manufacturer.",
        "OK": "OK",
        "CANCEL": "CANCEL",
        "YES": "YES",
        "NO": "NO",
        "ABORT": "ABORT",
        "RETRY": "RETRY",
        "IGNORE": "IGNORE",
        "Save successful": "Save succeeded.",
        "Save failed": "Save failed.",
        "Downloading, please wait": "Download in progress. Please wait.",
        ",upgrade now?": ",upgrade now?",
        "Level data save error": "Failed to Save Leveling Data.",
        "ERROR: Printer no response": "ERROR: Printer not Responding.",
        "ERROR: Printer password error": "ERROR: Incorrect Printer Password.",
        "ERROR: Printer connected by other clients": "ERROR: Printer is being used by other users.",
        "ERROR: Printer none certification": "ERROR: Printer is not certified.",
        "Connection OK": "Connection OK.",
        "Connection Error": "Connection Error.",
        "Activation is successful, please restart the printer": "Activation succeeded. Please restart the printer.",
        "Can not Save more than 4 millon facets model": "Cannot save models with more than 4 million facets.",
        "No Model Selected":"No model is selected",
        "warning!":"Warning!",
        "    Delete Selected Model?":"    Delete Selected Models?",
        "    Delete All Models?":"    Delete all of Models?",
        "Please close the front door": "Please Close the Front Door.",
        "Model is too large! Can not Load": "Model is too large. Loading Failed",
		"Loading Failed":"Loading Failed!",
        "Print job stopped at ": "Print Job Stopped at layer No.",
        "th layer, resume the print?": ". Resume the Print Job?",
        "ERROR: Can't resume the broken print job": "ERROR: Cannot Resume the Stopped Print Job.",
        "ERROR: Data transfer failed, try again?": "ERROR: Data Transfer Failed. Try again?",
        "OpenGL Version Too Low! Check your Graphic Drivers!": "Please upgrade OpenGL, and check your graphic card drivers!",
        "ERROR: Printer SN Error": "ERROR: Printer Serial Number Error",
        "ERROR: Unknow error": "ERROR: Unknown Error",
        "ERROR: Invalide activekey": "ERROR: Invalid Activation Key",
        "ERROR: No factory actived": "ERROR: Not Factory Activated",
        "ERROR: Active error,wrong key": "ERROR: Activation Error. Invalid Key",
        "ERROR: The server returns the activation code to parse the JSON failed": "ERROR: Activation data returned from server failed.",
        "ERROR: The server failed to return the activation code": "ERROR: The server failed to return the activation code",
        "ERROR: Failed to get the check code from the printer": "ERROR: Failed to get the checksum data from the printer",
        "ERROR: The current state of activation is not factory activation": "ERROR: The current activation status is not factory activation",
        "ERROR: Failed to obtain an active state": "ERROR: Failed to obtain the activation status.",
        "ERROR: Model out of print bound": "ERROR: Model out of Bound of Print Area",
        "ERROR: Calibration Failure": "ERROR: Calibration Failed",
        "ERROR: Server connection failed": "ERROR: Server Connection Failed",
        "ERROR: Verification Failed,Please download activation package": "ERROR: Verification Failed. Please Download Activation Package",
        "[YES] Perf Board\r\n[NO] Flex Board": "[YES] Perf Board\r\n[NO] Flex Board",
        "Please Select The Type Of Plat": "Please Select the Type Of Plat",
        "ERROR: Temperature is low": "ERROR: Temperature is Low",
        "Do you want to keep current model?": "Do you want to keep current model?"
    },
    "graphic": {
        "Filepath: ": "File Path: ",
        "Size(mm): ": "Size(mm): ",
        "Min-Size(mm): ": "Min-Size(mm): ",
        "Max-Size(mm): ": "Max-Size(mm): ",
        "Vertex Number: ": "Vertex Number: ",
        "Facet Number: ": "Facet Number: ",
	"Volume: ": "Volume: ",
        "Copying...":"Copying Models ...",
        "Saveing...":"Saving Models ...",
        "has scaled from inch unit to mm unit!":"has scaled from inch unit to mm unit!",
        "Property":"Property",
		"Copy":"Copy",
		"1 model":"1 Copy",
		"2 model":"2 Copys",
		"5 model":"5 Copys",
		"Delete":"Delete",
		"Delete All":"Delete All",
		"Select All":"Select All",
		"UnSelect All":"Unselect All",
		"Initialize View":"Initialize View",
		"Rotate By Models Center":"Rotate around the Center of Models",
		"Exit":"Exit"
    },
    "image_front": {
        "_Model_Height":"Model Height",
        "_Base_Height":"Base Height",
        "_Style":"Style",
        "_Model_Size":"Model Size",
        "_Unit":"Unit(mm)",
        "_Pen_Size":"Pen Size",
        "_Pen_Color":"Pen Color",
        "_Pen_Type":"Pen Type",
        "_Erase_Size":"Erase Size",
        "_Font":"Font",
        "_Font_Size":"Font Size",
        "_Font_Color":"Font Color",
        "_Constrain":"Constrain",
        "_Tools":"Tools",
        "_Setting":"Setting",
        "_Previous":"Previous",
        "_Apply":"Apply"
    },
}
