var english={
	"name": {
		"version": "2.0",
		"date": "2017-08-21",
		"name": "en"
	},
	"_front": 
		"Cancel": "Cancel",
		"Confirm": "Confirm",
		"About_Us": "About Us",
		"Account": "Account",
		"UP": "UP",
		"Libiray": "Library",
		"Help": "Help",
		"My_Account": "My Account",
		"Setting": "Setting",
		"Skin": "Skin",
		"Language": "Language",
		"Current_Language": "Current Language",
		"Printer": "Printer",
		"No_UP_printers_found": "No printers found",
		"Printer_Name_Cannot_Be_Empty": "Printer Name Cannot Be Empty.",
		"Failed_to_locate_WiFi": "Failed to locate WiFi",
		"Set_Success": "Set Succeeded",
		"Please_Enter_Password": "Please Enter Password",
		"Upgrade": "Upgrade",
		"Current": "Current",
		"Your_System_is_UPtodate": "Your System is UP-to-date",
		"Remind_me_of_the_new_version": "Remind me of the new version",
		"Update": "Update",
		"Privacy_Policy": "Privacy Policy",
		"privacy": "Please review Tiertime Privacy Policy to know about the details of data collection of Tiertime.You can choose to turn on or off the data collection function base on your preference.",
		"Details": "Details",
		"Skin_Color": "Skin Color",
		"Model_Color": "Model Color",
		"Basic": "Basic",
		"Login": "Login",
		"Username_or_Email": "Username or Email",
		"Sign_In": "Sign In",
		"Sign_Up": "Sign Up",
		"Forgot_Password": "Forgot Password?",
		"Login_Failed": "Login Failed",
		"User_Account_has_not_been_Activated": "User Account has not been Activated",
		"User_does_not_Existed": "User does not Existed",
		"Password_is_Incorrect": "Password is Incorrect",
		"Please_enter_your_username_and_password": "Please enter your username and password",
		"Please_enter_user_name": "Please enter user name",
		"Please_enter_your_password": "Please enter your password",
		"Network_Problems_and_Please_Try_Later": "Network Problems and Please Try Later",
		"Login_Timeout": "Login Timeout",
		"Printer_Management": "Printer Management",
		"Serial_Number": "Serial Number",
		"Activation_Status": "Activation Status",
		"Binding_Status": "Binding Status",
		"Activate": "Activate",
		"Activated": "Activated",
		"Bind": "Bind",
		"Unbind": "Unbind",
		"Success": "Success",
		"Unbind_Successfully": "Unbind Successfully",
		"Failed_to_Unbind": "Failed to Unbind",
		"Binding_Successfully": "Binding Successfully",
		"Activation_Succeeded": "Activation Succeeded",
		"Sign_out": "Sign out",
		"Username": "Username (3-20 Characters Starting with a Letter)",
		"Emailenter": "Email (Enter an Email Address)",
		"Password": "Password (6-32 Characters)",
		"Confirm_Password": "Confirm Password (Input Password Again)",
		"Registration_means_you_agree_with": "Registration means you agree with",
		"Tiertime_End_User_Agreement": "《Tiertime End User Agreement》",
		"Invalid_Username": "Invalid Username",
		"Invalid_Email_Address": "Invalid Email Address",
		"Invalid_Password": "Invalid Password",
		"Passwords_Do_Not_Match": "Passwords Do Not Match",
		"Registration_Successful": "Registration Successful",
		"Congratulations": "Congratulations",
		"success_text": "Registration is successful. An activation code has been sent to your email account. Please click the link in your email to activate your account.",
		"Email": "Email",
		"Error": "Error",
		"Email_or_Username_Error": "Email or Username Error",
		"An_email_to_reset_your_password_has_been_sent_to_your_email_address": "An email to reset your password has been sent to your email address",
		"Failed_to_Reset_Password": "Failed to Reset Password",
		"Home": "Home",
		"Import_Model_or_Image": "Import Model or Image",
		"Print": "Print",
		"Initialize_Printer": "Initialize Printer",
		"Calibrate": "Calibrate",
		"Maintenance": "Maintenance",
		"Move": "Move",
		"Scale": "Scale",
		"More": "More",
		"View": "View",
		"Undo": "Undo",
		"Auto_Place": "Auto Place",
		"Rotate": "Rotate",
		"Mirror": "Mirror",
		"Save_Model": "Save Model",
		"Reset_to_Default": "Reset to Default",
		"Fix_Errors": "Fix Errors",
		"Merge": "Merge",
		"Delete": "Delete",
		"Top_View": "Top View",
		"Bottom_View": "Bottom View",
		"Back_View": "Back View",
		"Free_View": "Free View",
		"Right_View": "Right View",
		"Front_View": "Front View",
		"Left_View": "Left View",
		"Wait_a_moment": "Wait a moment...",
		"Range_is_from": "Range is from",
		"No_Axis_Chosen": "No Axis Chosen",
		"Add": "Add",
		"Add_Picture": "Add Picture",
		"Add_Mode": "Add Model",
		"Saving": "Saving",
		"Printer_Setting": "Printer Setting",
		"Normal": "Normal",
		"Layer_Thickness": "Layer Thickness",
		"Infill": "Infill",
		"Quality": "Quality",
		"Fine": "Fine",
		"Fast": "Fast",
		"Turbo": "Turbo",
		"Option": "Option",
		"Preference": "Preference",
		"Dormancy": "Sleep",
		"Preview": "Preview",
		"Select_Saved_Slot": "Select Saved Slot",
		"Reprint": "Reprint",
		"Slot": "Slot",
		"Number": "NO.",
		"Time": "Time",
		"Date": "Date",
		"Choose": "Choose",
		"Part": "Part",
		"Surface": "Surface",
		"Angle": "Angle",
		"Support": "Support",
		"Dense": "Dense",
		"Area": "Area",
		"Space": "Space",
		"No_Raft": "No Raft",
		"No_Support": "No Support",
		"Stable_Support": "Stable Support",
		"Others": "Others",
		"Unsolid_Model": "Unsolid Model",
		"Thin_Wall": "Thin Wall",
		"Preheat": "Preheat",
		"Default": "Default",
		"Calibration": "Calibration",
		"Platform_Calibration": "Platform Calibration",
		"Manual": "Manual",
		"Auto_Level": "Auto Level",
		"Reset": "Reset",
		"Nozzle_Height": "Nozzle Height",
		"Set": "Set",
		"Nozzle_Detect": "Nozzle Detect",
		"Demo_Op": "Demo Op.",
		"Demo_Op_Over": "Demo Op. Over",
		"Set_nozzle_height_is": "Set nozzle height is:",
		"Compensation": "Compensation",
		"Set_Nozzle_Height_as": "Set Nozzle Height as ",
		"Extrude": "Extrude",
		"Withdraw": "Withdraw",
		"Stop": "Stop",
		"Material": "Material",
		"Weight": "Weight",
		"Customized": "Customized",
		"Customized_Material": "Customized Material",
		"Name": "Name",
		"Nozzle": "Nozzle(℃)",
		"Platform": "Platform(℃)",
		"Process": "Process",
		"Please_sign_in_your_account": "Please sign in your account",
		"Material_Name_Duplicated": "Error:Material Name Duplicated",
		"Only_7_Materials_Allowed": "Only 7 Materials Allowed",
		"Fields_can_not_be_Empty": "Fields can not be Empty",
		"Stop_Printing": "Stop Printing",
		"Pause": "Pause",
		"Resume": "Resume",
		"Stop_Preview": "Stop Preview",
		"Time_Left": "Time Left",
		"h": "h",
		"m": "m",
		"s": "s",
		"Slicing": "Slicing ",
		"Sending": "Sending ",
		"offical_initerface": "Official Material",
		"series_number": "Serial Number",
		"serial_password": "Password",
		"please_series_number": "Please Enter The Serial Number",
		"My_model": "My Model",
		"Public_model": "Moshop",
		"Self_model": "Private",
		"Save_model": "Liked",
		"Share_model": "Published",
		"Buy_model": "Purchased",
		"My_print": "My 3D Printer",
		"Find_all_print": "View All Printers",
		"User_number": "User Credits",
		"Change_password": "Modify Password",
		"upload_model": "Upload Model",
		"upload": "Upload",
		"upload_list": "Upload List",
		"readmessage": "Preparing Data......",
		"All": "All",
		"Free": "1 Point",
		"Pay": ">1 Point",
		"Model_parameter": "Model Parameters",
		"Model_Size": "Size",
		"Model_price": "Points",
		"Model_filder": "File",
		"Print_count": "Print Times",
		"Model_buy": "Buy",
		"Model_save": "Like",
		"Model_al_save": "Liked",
		"Model_download": "Download",
		"Model_deleat": "Delete",
		"Model_desript": "Descriptions",
		"Model_name": "Name",
		"Download_on": "Download",
		"Model_share": "Share",
		"Cancel_upload": "Cancel Publish Process",
		"All_download": "Download All",
		"All_open": "Open All",
		"Model_attr": "Model Attributes",
		"Model_information": "Model Infomation",
		"Filepath": "File Path:",
		"Size": "Model Size:",
		"Min_Size": "Min Pos:",
		"Max_Size": "Max Pos:",
		"Vertex_Number": "Vertex Number:",
		"Facet_Number": "Facet Number:",
		"Volume": "Volume:",
		"Surface_Area": "Area:",
		"Inch": "Inch",
		"Mm": "mm",
		"Alerady_buy": "Purchased",
		"Manage" : "Manage",
		"Model_unit": "Unit:",
		"Auto_height_end": "Nozzle height detection ended",
		"Flex_plat": "Flex",
		"Ward_plat": "Perforated",
		"Model_upload": "Publish",
		"Unlimited": "Unlimited",
		"Error_prompt": "Error",
		"Connection_failed": "Connection failed",
		"User_and_password": "User name and password can not be empty",
		"User_and_password_already": "User name or mailbox already exists",
		"Calibration_failure_temp_hot": "Calibration failed, nozzle temperature is too high",
		"Member_login_in_auto": "Auto Login",
		"Model_list_nav": "Navigation",
		"Model_share_cancle":  "Canceled",
		"Keep_on_download": "Continue",
		"Model_preparing":"Preparing data, can not close",
		"LatestVersion": "Latest Version V.",
		"Failed_to_bind": "Binding failed",
		"Custom_material_information_empty":"Custom material information can not be blank",
		"Clear_cache": "Clean up cache",
		"Clear_download_model": "Clear downloaded models",
		"Clear_cache_file": "Clear cache file",
		"Compensation_height": "Nozzle offset",
		"Current_nozzle_height_print": "Nozzle height",
		"Model_insert": "Insert",
		"Advanced_print": "Advanced Print",
		"Pause_position": "Pause position",
		"Pause_height": "Height",
		"Print_cao": "Print slot",
		"Pause_print_exame": "Enter the height (mm) to be paused For example: 7.6",
		"Model_audit": "Under review",
		"Model_re_publish": "Republish",
		"Cancel_clear_up": "Cancel",
		"Clear_finish": "Cleanup Complete",
		"Nozzle_diameter": "Nozzle Diam",
		"Infill_wrap": "Shell",
		"Infill_surface": "Surface",
		"Infill_style1": "13%",
		"Infill_style2": "15%",
		"Infill_style3": "20%",
		"Infill_style4": "65%",
		"Infill_style5": "80%",
		"Infill_style6": "99%",
		"Manual_activation": "Manual activation",
		"Manual_file": "Please load activeCode.act file to activate the printer",
		"Copy_message": "Copy information to clipboard",
		"Manual_fail": "Failed to return activation code from server",
		"Manual_download": "Loading",
		"Manual_connecting": "Activating, please wait ...",
		"Platform_leval": "Level Calibration",
		"Platform_vertival": "Vertical Calibration",
		"Model_default_color": "Default",
		"Model_color_design": "Edit",
		"Manual_have_code": "If you already have an activation code, you can try",
		"Manual_copy_success": "Copy successful",
		"Infinite_print_price": "Unlimited",
		"Once_print_price": "One time",
		"Model_print_price": "Print Points",
		"Print_infinite": "Unlimited",
		"Model_buy_times": "Purchases",
		"Manual_email": "If you do not have this file, you can log in",
		"Model_publish_limited": "Unlimited print prices must be higher than a single print price",
		"Manual_pass_information": "Copy the following information:",
		"Manual_get_code":"Gets the active file ActiveCode.act, activates the printer manually",
		"Colud_Print":"Printing with Cloud Parameters",
		"Manual_active_login_font": "You can sign in",
		"Manual_get_code_select": "Get activeCode.act",
		"Manual_send_email": "Send the following information to zhangyh@tiertime.net to get:",
		"Manual_select_hide": "Collapse",
		"Check_upload_ups":"Can not upload protected model",
		"Model_Skin_Color": "Default Color",
		"Easy_peel": "Easy to peel",
		"Email_or_password_Error":"Please enter the correct email / username and password",
		"Model_count_number": "The number of prints can not be less than 1",
		"Local_model": "Local",
		"Load_check": "Load selected",
		"Material_type": "Type",
		"Material_history": "History",
		"Account_User_Already": "User name already exists",
		"Account_Email_Already": "Email already exists",
		"ABS_Cloud_Print":"Using ABS cloud parameters to print",
		"network_font_content":"Network Settings",
		"network_fast_font":"Quick Link",
		"network_normal_font":"Normal Link",
		"Network_Problems_and_register":"Registration Timeout",
		"Network_Problems_and_regpassword": "Reset Password Timeout",
		"Network_Problems_and_exit": "Exit Current Account Timeout",
		"password_input":"Please enter",
		"password_password":"'s password",
		"choose_better_thrick":"Choose nozzle 0.2mm will get a better job",
		"stop_print_message":"Confirm to stop the current job?",
		"Platform_model": "Model Calibration",
		"Platform_axial": "XYZ Axial Calibration",
		"Axial": "Axial",
		"Axial_descript": "Notes",
		"Axial_fact": "S1: Theoretical Value",
		"Axial_test": "M1: Actual Value",
		"Axial_alert_message": "Theoretical value or actual value can not be 0",
		"Choose_floor": "Print Board",
		"Ward_and_Flex": "Perforated+Flex",
		"Glass_plat": "4mm Glass Plate",
		"wifi_high_setting":"Advanced Settings",
		"Usb_connect_network": "Link",
		"Back": "Return",
		"Load_standrd_model": "Load The Calibration Model",
		"version_description": "Version Declaration",
		"reading_print_parmes": "Getting print parameters",
		"link_other_print": "Connect to other printers",
		"connect_print_by_ip": "To connect to the printer, enter it's IP address and the optional printer password",
		"connect_other_network": "Join other networks",
		"m1_and_s1": "The difference between m1 and s1 can not exceed +-1",
		"circle_floor_state": "Roate Face to Bottom",
		"version_loading": "Downloading ...",
		"model_radius": "Radius：",
		"model_height": "Height：",
		"model_width": "Width：",
		"model_length": "Side Length：",
		"model_long": "Length：",
		"model_parm_font": "Model Parameter",
		"network_type": "Type",
		"network_address": "IP",
		"network_port": "Port",
		"network_user": "User Name",
		"network_test": "Test",
		"network_nouse_agent": "Do Not Use Proxy",
		"network_use_http": "HTTPS Proxy",
		"contour_linewidth": "Extrusion Width",
		"height_button_font": "Click the model face you want to be the bottom,then press 'Confirm'",
		"loop_input_error": "Input range is -0.15 to + 0.25mm for the default contour line width",
		"network_testing": "Test ...",
		"address_and_port":"Address or port can not be empty",
		"Model_radius_limit": "The outer radius must be greater than the inner radius",
		"forbiddrn_User_Login": "Login forbidden，please contact us",
		"model_cart": "Categories",
		"input_model_cart": "Please select model category",
		"account_setting":"Account Settings",
		"print_refresh": "Refresh",
		"message_problem_type": "Type of feedback problem：",
		"software_problem": "Software Problem",
		"printer_problem": "Printer Failure",
		"print_quality": "Print Quality",
		"limit_input": "Limit Input",
		"message_font": "Words",
		"message_email": "Contact：",
		"printer_sn": "Printer SN：",
		"message_load_img": "Upload Screenshots：",
		"please_load_img": "Please upload pictures",
		"please_input_sn": "Please enter",
		"message_looking": "Browse",
		"message_send": "Submit",
		"problem_and_information": "Questions and Comments：",
		"model_spcview": "Display Mode",
		"model_pou": "Cliplane",
		"edit_parames": "Parameters",
		"edit_slide": "Slides：",
		"top_radius": "Top Radius：",
		"bottom_radius": "Bottom Radius：",
		"out_radius": "Outer radius：",
		"in_radius": "Inner radius：",
		"edit_points": "Points：",
		"edit_font": "Font：",
		"edit_text": "Text：",
		"model_edit_font": "Model Edit",
		"message_message": "Feedback",
		"edit_slide_count": "The number of sides input must be 3-12",
		"edit_slide_point": "The range of points input must be 5-30",
		"edit_top_botom": "The bottom and top radii can not be 0",
		"spc_one": "Wireframe",
		"spc_two": "Solid",
		"spc_thr": "Transparent",
		"spc_for": "Solid and Wireframe",
		"circle_to_floor": "Drop down on the floor",
		"message_send_succ": "Send successful",
		"message_send_fail": "Send failed",
		"message_sending": "Send...",
		"input_correct_email": "Please enter a valid email address",
		"upload_succ": "Upload successful",
		"upload_fail": "Upload failed",
		"model_reserze": "Reverse",
		"please_input_your_num": "Please enter your contact information"
	},
	"print": {
		"PrinterStatus-1": "Printer not Connected",
		"PrinterStatus0": "Printer not Initialized",
		"PrinterStatus1": "Printer Ready",
		"PrinterStatus2": "Print Job in Progress",
		"PrinterStatus3": "Print Job Paused",
		"PrinterStatus4": "Nozzle Error",
		"PrinterStatus5": "Motion System Error",
		"PrinterStatus6": "Print Job Finished",
		"PrinterStatus7": "Print Job Stopped",
		"PrinterStatus8": "Nozzle Too Hot",
		"PrinterStatus9": "Nozzle Too Cool",
		"PrinterStatus10": "Platform Too Hot",
		"PrinterStatus11": "tt_reserved_1",
		"PrinterStatus12": "tt_reserved_2",
		"PrinterStatus13": "tt_reserved_3",
		"PrinterStatus14": "tt_reserved_4",
		"PrinterStatus15": "System Powered ON",
		"PrinterStatus16": "SD Card Error",
		"PrinterStatus17": "SD Card Write Error",
		"PrinterStatus18": "SD Card Read Error",
		"PrinterStatus19": "Save to SD Card",
		"PrinterStatus20": "Joggle Error",
		"PrinterStatus21": "Copyright Limitation",
		"PrinterStatus22": "Print Number Limitation",
		"PrinterStatus23": "Communication Error",
		"ERROR": "ERROR",
		"ERROR: Task cannot be performed during printing": "ERROR: Task cannot be performed during on going print jobs.",
		"ERROR: Incorrect material": "ERROR: Incorrect Material.",
		"ERROR: Printer status error": "ERROR: Printer Status Error.",
		"ERROR: Printer connection error": "ERROR: Printer Connection Error.",
		"ERROR: Data transfer failure": "ERROR: Data Transfer Failure.",
		"ERROR: Printer is busy,please stop and try again": "ERROR: Printer is busy. Please wait until it stops and then try again.",
		"ERROR: Printer material shortage,still continue?": "ERROR: Printer is short of material, still continue?",
		"ERROR: Printer support material shortage,still continue?": "ERROR: Printer is short of support material, still continue?",
		"Correct range":"Correct range",
		"Repeat last print?": "Repeat Last Print?",
		"ERROR: Other error ": "ERROR: Other Errors.",
		"Language test": "Language Test",
		"Are you sure to stop the print job?": "Confirm to stop the current job?",
		"Found a new version": "A new version of software has been found",
		",download it immediately?": ",download it immediately?",
		"[YES]: Update immediately": "[YES]: Update Immediately",
		"[NO]: Remind me later": "[NO]: Remind Me Later",
		"[CANCEL]: Switch off update reminder": "[CANCEL]: Switch Off Update Reminder",
		"Note: Download will be running in the background, after the completion of the notice": "Note: Download will be running in the background. You will be notified after the completion .",
		"Update": "Update",
		"No new version": "No New Version.",
		"ERROR: Temperature is too high": "ERROR: Temperature is too high.",
		"ERROR: Sensor not connected": "ERROR: Sensor is not connected.",
		"ERROR: Calibration Failure": "ERROR: Calibration failed.",
		"ERROR: Printer is busy": "ERROR: Printer is busy.",
		"Success，Please reset nozzle height before printing": "Success: Please reset the nozzle height before printing.",
		"ERROR: Printer error": "ERROR: Printer Error.",
		"Print: ": "Print: ",
		"Material: ": "Material: ",
		"g": "g",
		"H": "H",
		"M": "M",
		"S": "S",
		"ERROR: Templete directory get error": "ERROR: Failed to locate the temporary directory.",
		"ERROR: Create dir error": "ERROR: Failed to create directory",
		"ERROR: Copy UpdateFile Error_APP": "ERROR: Failed to Copy Update File_APP",
		"ERROR: Copy UpdateFile Error_DLL": "ERROR: Failed to Copy Update File_DLL",
		"ERROR: Nozzleheight set error": "ERROR: Failed to Set Nozzle Height",
		"ERROR:Model does not exist": "ERROR: Model not found",
		"Activation": "Activation",
		"Please activate the printer in time to use the full printer functions": "Please activate the printer to use the full power of printers",
		"Activation state error, need to return to the factory": "Failed to activate the printer. Please contact the manufacturer.",
		"OK": "OK",
		"CANCEL": "CANCEL",
		"YES": "YES",
		"NO": "NO",
		"ABORT": "ABORT",
		"RETRY": "RETRY",
		"IGNORE": "IGNORE",
		"Save successful": "Save succeeded.",
		"Save failed": "Save failed.",
		"Downloading, please wait": "Download in progress. Please wait.",
		",upgrade now?": ",upgrade now?",
		"Level data save error": "Failed to Save Leveling Data.",
		"ERROR: Printer no response": "ERROR: Printer not Responding.",
		"ERROR: Printer password error": "ERROR: Incorrect Printer Password.",
		"ERROR: Printer connected by other clients": "ERROR: Printer is being used by other users.",
		"ERROR: Printer none certification": "ERROR: Printer is not certified.",
		"Connection OK": "Connection OK.",
		"Connection Error": "Connection Error.",
		"Activation is successful, please restart the printer": "Activation succeeded. Please restart the printer.",
		"Can not Save more than 4 millon facets model": "Cannot save models with more than 4 million facets.",
		"No Model Selected": "No model is selected",
		"warning!": "Warning!",
		"    Delete Selected Model?": "    Delete Selected Models?",
		"    Delete All Models?": "    Delete all of Models?",
		"Please close the front door": "Please Close the Front Door.",
		"Model is too large! Can not Load": "Model is too large. Loading Failed",
		"Loading Failed": "Loading Failed!",
		"Print job stopped at ": "Print Job Stopped at layer No.",
		"th layer, resume the print?": ". Resume the Print Job?",
		"ERROR:  Can not resume the broken print job": "Error: Can not resume the suspended print",
		"ERROR: Data transfer failed, try again?": "ERROR: Data Transfer Failed. Try again?",
		"OpenGL Version Too Low! Check your Graphic Drivers!": "Please upgrade OpenGL, and check your graphic card drivers!",
		"ERROR: Printer SN Error": "ERROR: Printer Serial Number Error",
		"ERROR: Unknow error": "ERROR: Unknown Error",
		"ERROR: Invalide activekey": "ERROR: Invalid Activation Key",
		"ERROR: No factory actived": "ERROR: Not Factory Activated",
		"ERROR: The server failed to return the activation code": "ERROR: The server failed to return the activation code",
		"ERROR: Failed to get the check code from the printer": "ERROR: Failed to get the checksum data from the printer",
		"ERROR: Failed to obtain an active state": "ERROR: Failed to obtain the activation status.",
		"ERROR: Model out of print bound": "ERROR: Model out of Bound of Print Area",
		"ERROR: Server connection failed": "ERROR: Server Connection Failed",
		"ERROR: Verification Failed,Please download activation package": "ERROR: Verification Failed. Please Download Activation Package",
		"ERROR: Temperature is low": "ERROR: Temperature is Low",
		"Do you want to keep current model?": "Do you want to keep current model?",
		"ERROR: Image read failed": "Error: Image import failed",
		"Multiple": "Multiple",
		"ERROR：Please select the model you need to upload": "Error: Please select the model you need to uplaod",
		"Initialize_Printer": "Initialize Printer",
        "ERROR: Material modification failure": "ERROR: Material modification failure",
        "Price":"Price",
		"Point":"Point",
		"Sure to buy":"Do you want get this project",
		"ERROR: Upload Error": "ERROR: Upload Error",
        "ERROR: Network Disconnection": "ERROR: Network Disconnection",
        "ERROR: Cancel publish failure":"ERROR: Cancel publish failure",
        "The printer does not support this feature":"The printer does not support this feature",
        "Print finished, please take out the model":"Print finished, please take out the model",
        "Cancel":"Cancel",
		"Not Prompt":"Not Prompt",
		"No material detected, please replace it":"No material detected, please replace it",
		"ERROR: Publish failure":"ERROR: Publish failure",
		"ERROR:Gcode failed to run":"ERROR:Gcode failed to run",
		"Run File":"Run file",
		"ERROR: Input Not Valid":"ERROR: Input Not Valid",
		"Select active file":"Select active file",
		"ERROR: X1 Or X2 Input Error":"ERROR: X1 Or X2 Input Error",
		"ERROR: Z Or H Input Error":"ERROR: Z Or H Input Error",
		"ERROR: Save Error":"ERROR: Save Error",
		"ERROR: User Not Login":"ERROR: User Not Login",
		"ERROR: Model validation failure":"ERROR: Model validation failure",
		"Can Not Open File!":"Can Not Open File!",
		"Can Not Verify File!":"Can Not Verify File!",
		"User Does Not Match!":"User Does Not Match!",
		"ERROR: Clear SD card error":"Error: clean up the SD card error",
		"Clear SD card ok":"Clean SD card successfully",
		"Not finish":"Transmission is not completed",
		"System not ready":"System not ready",
		"Null layer":"The model has empty layers",
		"Part material insufficient for the print job":"Part material insufficient for the print job",
		"Support material insufficient for the print job":"Support material insufficient for the print job",
		"Fail to send cmd to printer":"Fail to send cmd to printer",
		"Printer error":"Printer error",
		"Can not load buildstart program":"Can not load buildstart program",
		"Lost WIFI packages":"Lost WIFI packages",
		"Null temperature setting":"Null temperature setting",
		"License verify failed":"License verify failed",
		"ERROR: Slicing error":"ERROR: Slicing Error",
		"Connection Success":"Connection Success",
		"ERROR: Connection Failed":"Error: Connection Failed",
		"Unlimited": "Unlimited",
		"Keep_on_download": "Continue",
		"ERROR: Feedback ERROR":"Error: Feedback submission failed",
		"Crashed. Do you upload error messages?":"Crashed. Do you upload error messages?",
		"ERROR: Printing,cannot stop heating":"Error: printing, can not stop heating",
		"Fatal Error":"Fatal Error"
	},
	"graphic": {
		"Invalid":"Invalid",
		"Filepath: ": "File Path: ",
		"Size: ": "Size: ",
		"Min-Size: ": "Min-Size: ",
		"Max-Size: ": "Max-Size: ",
		"Vertex Number: ": "Vertex Number: ",
		"Facet Number: ": "Facet Number: ",
		"Volume: ": "Volume: ",
		"Copying...": "Copying Models ...",
		"Saveing...": "Saving Models ...",
		"has scaled from inch unit to mm unit!": "Model is too small,Enlarged by 25.4 times!",
		"Property": "Property",
		"Merge": "Merge Model",
		"Copy": "Copy",
		"Delete": "Delete",
		"Delete All": "Delete All",
		"Select All": "Select All",
		"UnSelect All": "Unselect All",
		"Initialize View": "Initialize View",
		"Rotate By Models Center": "Rotate around the Center of Models",
		"Exit": "Exit",
		"app is not verified":"App is not verified",
		"The file is damaged": "The file is damaged",
		"current models contain protected model! can not do this operation!":"Current models contain protected model! Can not do this operation!",
		"UnKnown ERROR!Please Contact TierTime!":"Unknown error!Please contact us!",
		"Copy Number: ": "Copy Number",
		"Copy Model": "Copy Model",
		"1 model": "1 Copy",
		"2 model": "2 Copys",
		"3 model": "3 Copys",
		"4 model": "4 Copys",
		"5 model": "5 Copys",
		"6 model": "6 Copys",
		"7 model": "7 Copys",
		"8 model": "8 Copys",
		"custom": "Customized",
		"Voxelization": "Voxelization",
		"Edit":"Edit",
		"Voxel Size":"Voxel Size"
	},
	"image_front": {
		"_Model_Height": "Model Height",
		"_Base_Height": "Base Height",
		"_Style": "Style",
		"_Model_Size": "Model Size",
		"_Unit": "Unit(mm)",
		"_Pen_Size": "Pen Size",
		"_Pen_Color": "Pen Color",
		"_Pen_Type": "Pen Type",
		"_Erase_Size": "Erase Size",
		"_Font": "Font",
		"_Font_Size": "Font Size",
		"_Font_Color": "Font Color",
		"_Constrain": "Constrain",
		"_Tools": "Tools",
		"_Setting": "Setting",
		"_Previous": "Previous",
		"_Apply": "Apply",
		"_Go_back": "Back",
		"_Pen": "Pen",
		"_Rubber": "Eraser",
		"_Text": "Text",
		"_Cut": "Crop",
		"_Toggle_color": "Toggle color",
		"_choose_model_base": "Select Base",
		"_image_image": "Picture",
		"_image_loop": "Lampshade",
		"_image_pic": "Frame",
		"_image_relative": "Relative"
	},
	"image": {}
}
